name: OCI VM Status Daily Report

on:
#  schedule:
#    - cron: '0 0,12 * * *'  # Berjalan jam 8:00 AM & 8:00 PM (MYT / UTC+8)
  workflow_dispatch:

jobs:
  check-vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run VM Status Checker
        env:
          OCI_TENANCY: ${{ secrets.OCI_TENANCY }}
          OCI_USER: ${{ secrets.OCI_USER }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_KEY_CONTENT: ${{ secrets.OCI_KEY_CONTENT }}
          OCI_COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python python_script/check_vm_status_telegram.py
